GET http://127.0.0.1:8000/api/task-list HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
X-XSRF-TOKEN: eyJpdiI6Im85clp6aDhKRGhhbHg3YzY4QklZK3c9PSIsInZhbHVlIjoiaGZjdXNudktCN2FnZkpVR1pVRGtQN0NLcko1YzVxVVBZNEtDNnlDVFcwRDBUN0VSdjVYMGE3R1FOdGFvcmorQTlUL2dEcHVVaEdqczIxQ1lqVmYvK2VSTUVIUkVYZWVIODRCVGVaY2o3QzlwVDljY0pOYXRubUsxRjNwNjNHZTAiLCJtYWMiOiIwN2NiOGI1NWY1MjA2MjQwYWVlYWYyZDdkODc0MzFlMTFiNWMyMTQ1OWIyMzVlMTU4YzBkMjNjMmMxMGU0M2U0In0=




